- name: ping and message the server
  hosts: web
  tasks: #list of tasks
  - name: message
    ansible.builtin.debug:
      msg: 'Hello-Mike-Check'
  - name: ping the server
    ansible.builtin.ping:

# Comment
# Trail 